### ISSUE TITLE
Cannot create an external net for OpenStack cluster 

### ISSUE THREAD

**Issue by mmuppidi** [UTSA-OCI/OCI-OpenStack-Ansible#9]
Tried to create a external network for OpenStack cluster, this works fine for the chameleon cloud environment but I have problems with our internal servers. What am I doing wrong ? Any suggestions @elextro 

```
root@aio1_neutron_agents_container-08fe4377:~# neutron net-create --provider:physical_network=flat --provider:network_type=flat --shared --router:external my_os_ext_net
Unable to create the flat network. Physical network flat is in use.
```

**Comment by disml2024** [comment]
I think the "--provider:physical_network" should specify the Name of the physical network over which the virtual network is implemented.  

The "flat" is more like a "--provider:network_type"?

**Comment by alextricity25** [comment]
Can you paste the output of these commands? 

cat /etc/neutron/plugins/ml2/ml2_conf.ini
and
neutron net-list
and
brctl show

Could you also try running the command with the --debug flag?

**Comment by alextricity25** [comment]
@zhuronghua OSCAR always configures the name of the physical provider network to be "flat". 
Here is the openstack_user_config.yml where it's configured:
https://github.com/cloudandbigdatalab/OSCAR/blob/master/openstack_deploy/openstack_user_config.yml.template#L45

Maybe it would be a good idea to change that. It can be a little confusing ;)

**Comment by disml2024** [comment]
@elextro Thanks!  your link explains alot.  I am expecting the output of the commands too.

I am not familiar about the Ansible approach.  Not sure if the "--router:external True" is an important one while creating external net.

**Comment by mmuppidi** [comment]
Here you go

```
root@aio1_neutron_agents_container-08fe4377:~# cat /etc/neutron/plugins/ml2/ml2_conf.ini
# Ansible managed: /opt/openstack-ansible/playbooks/roles/os_neutron/templates/plugins/ml2/ml2_conf.ini.j2 modified on 2015-11-05 18:48:15 by root on rack4-1



# Linux bridge agent VXLAN networks
[vxlan]


enable_vxlan = True
vxlan_group = 


# VXLAN local tunnel endpoint (container)
local_ip = 172.41.101.109


l2_population = True



# Linux bridge agent physical interface mappings
[linux_bridge]
physical_interface_mappings = flat:eth12


# Agent
[agent]
prevent_arp_spoofing = False

# L2 population
[l2pop]
agent_boot_time = 180


# Security groups
[securitygroup]
enable_security_group = True
enable_ipset = True
firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
```

```
root@aio1_neutron_agents_container-08fe4377:~# neutron net-list
+--------------------------------------+----------------+-----------------------------------------------------+
| id                                   | name           | subnets                                             |
+--------------------------------------+----------------+-----------------------------------------------------+
| 1cdbac67-c024-4a46-ba3b-7e2203b9e96b | my_private_net | 7510301f-0a47-482e-8627-a02562ddc489 192.168.1.0/24 |
| ff06c279-7de7-4c84-8838-6d150bc49e36 | internal       | 06de31a8-e154-495d-ba1a-0f6957b3dba9 192.168.1.0/24 |
| ad42ce5c-8823-46a2-832c-2f2f0d61daf1 | public_net     |                                                     |
+--------------------------------------+----------------+-----------------------------------------------------+
```

```
root@rack4-1:~# brctl show
bridge name bridge id       STP enabled interfaces
br-mgmt     8000.92a18e65ee8d   no      050849c8_eth1
                            08fe4377_eth1
                            138c0cd3_eth1
                            1c3680a1_eth1
                            20b69c7f_eth1
                            23362fc8_eth1
                            47f3b459_eth1
                            55467694_eth1
                            7794e559_eth1
                            81ee3e98_eth1
                            8dc04ff2_eth1
                            9cca065c_eth1
                            b44bf6a6_eth1
                            ba66ed31_eth1
                            bbd64132_eth1
                            br-storage-veth
                            br-vlan-veth
                            br-vxlan-veth
                            ce1b2afc_eth1
                            df24d9c8_eth1
                            e2a1dadd_eth1
                            e3ecaefa_eth1
                            eth0
                            fa7d8f39_eth1
                            ff9ee939_eth1
br-storage      8000.fa1ca87c8947   no      7794e559_eth2
                            ce1b2afc_eth2
                            em16
br-vlan     8000.aa2b7d4ce7a2   no      08fe4377_eth12
                            em17
br-vxlan        8000.e204e62f7043   no      08fe4377_eth10
                            em15
lxcbr0      8000.fe18b7201910   no      050849c8_eth0
                            08fe4377_eth0
                            138c0cd3_eth0
                            1c3680a1_eth0
                            20b69c7f_eth0
                            23362fc8_eth0
                            47f3b459_eth0
                            55467694_eth0
                            7794e559_eth0
                            81ee3e98_eth0
                            8dc04ff2_eth0
                            9cca065c_eth0
                            b44bf6a6_eth0
                            ba66ed31_eth0
                            bbd64132_eth0
                            ce1b2afc_eth0
                            df24d9c8_eth0
                            e2a1dadd_eth0
                            e3ecaefa_eth0
                            fa7d8f39_eth0
                            ff9ee939_eth0
```

```
root@aio1_neutron_agents_container-08fe4377:~# neutron net-create --provider:physical_network=flat --provider:network_type=flat --shared --router:external my_os_ext_net --debug
DEBUG: keystoneclient.session REQ: curl -g -i -X GET http://172.41.100.100:5000/v3 -H "Accept: application/json" -H "User-Agent: python-keystoneclient"
DEBUG: keystoneclient.session RESP: [200] content-length: 253 vary: X-Auth-Token server: Apache date: Mon, 09 Nov 2015 19:13:03 GMT content-type: application/json x-openstack-request-id: req-baac560c-fb1f-4e16-8c39-e6e08a55866f 
RESP BODY: {"version": {"status": "stable", "updated": "2015-03-30T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}], "id": "v3.4", "links": [{"href": "http://172.41.100.100:5000/v3/", "rel": "self"}]}}

DEBUG: stevedore.extension found extension EntryPoint.parse('table = cliff.formatters.table:TableFormatter')
DEBUG: stevedore.extension found extension EntryPoint.parse('shell = cliff.formatters.shell:ShellFormatter')
DEBUG: stevedore.extension found extension EntryPoint.parse('value = cliff.formatters.value:ValueFormatter')
DEBUG: neutronclient.neutron.v2_0.network.CreateNetwork get_data(Namespace(admin_state=True, columns=[], formatter='table', max_width=0, name=u'my_os_ext_net', prefix='', provider:network_type=u'flat', provider:physical_network=u'flat', provider:segmentation_id=None, request_format='json', router:external=True, shared=True, tenant_id=None, variables=[]))
DEBUG: keystoneclient.auth.identity.v3.base Making authentication request to http://172.41.100.100:5000/v3/auth/tokens
DEBUG: keystoneclient.session REQ: curl -g -i -X POST http://172.41.100.100:9696/v2.0/networks.json -H "User-Agent: python-neutronclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}4142ccfab5d45bfbe87adcd85e50149ac2cea230" -d '{"network": {"router:external": true, "name": "my_os_ext_net", "provider:physical_network": "flat", "admin_state_up": true, "provider:network_type": "flat", "shared": true}}'
DEBUG: keystoneclient.session RESP:
DEBUG: neutronclient.v2_0.client Error message: {"NeutronError": {"message": "Unable to create the flat network. Physical network flat is in use.", "type": "FlatNetworkInUse", "detail": ""}}
ERROR: neutronclient.shell Unable to create the flat network. Physical network flat is in use.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/shell.py", line 766, in run_subcommand
    return run_command(cmd, cmd_parser, sub_argv)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/shell.py", line 101, in run_command
    return cmd.run(known_args)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/common/command.py", line 29, in run
    return super(OpenStackCommand, self).run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/cliff/display.py", line 91, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/common/command.py", line 35, in take_action
    return self.get_data(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/neutron/v2_0/__init__.py", line 475, in get_data
    data = obj_creator(body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 102, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 571, in create_network
    return self.post(self.networks_path, body=body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 298, in post
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 211, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 185, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 70, in exception_handler_v20
    status_code=status_code)
Conflict: Unable to create the flat network. Physical network flat is in use.
```

**Comment by alextricity25** [comment]
Did you run "neutron net-create" after creating public_net? I bet you that the "public_net" network is using the same external neutron network(flat) and that's what is causing the problem. A single environment cannot have multiple flat external networks. What are you using public_net for?

**Comment by mmuppidi** [comment]
You are right. In the setup some one created the  "public_net" and thats what was causing the issue. I deleted the network using

```
neutron net-delete public_net
```

And then created "my_os_ext_net" It works fine. 
Thanks
